services:
  app:
    image: amazoncorretto:latest
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: TeamApril
      MYSQL_PASSWORD: 1234
      MYSQL_DB: agenda_db
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - gfg-mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: agenda_db
volumes:
  gfg-mysql-data:
